name: vibechan
description: "A modern, agnostic reader application"
publish_to: 'none'
version: 0.0.23

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # UI and Theming
  flex_color_scheme: ^8.2.0
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.1
  video_player: ^2.8.2
  chewie: ^1.7.5
  flutter_markdown: ^0.7.6+2
  shimmer: ^3.0.0

  # State Management and DI
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5
  get_it: ^8.0.3
  injectable: ^2.3.3

  # Routing
  go_router: ^14.8.1

  # Data Layer
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  sqflite: ^2.3.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  connectivity_plus: ^6.1.3

  # Utils
  logger: ^2.0.2+1
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  collection: ^1.18.0
  uuid: ^4.3.3
  file_picker: ^6.2.1

  # Player
  media_kit: ^1.1.11 # Primary package.
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5 # Native video dependencies.

  # Permissions
  permission_handler: ^11.4.0
  html: ^0.15.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  freezed: ^3.0.4
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  riverpod_generator: ^2.3.2
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
