version: 2.1

executors:
  flutter:
    docker:
      - image: ghcr.io/cirruslabs/flutter:3.29.2
    working_directory: ~/repo

jobs:
  build_android:
    executor: flutter
    steps:
      - checkout
      - run: flutter pub get
      - run:
          name: Build 64-bit Android APK
          command: flutter build apk --release --target-platform android-arm64
      - persist_to_workspace:
          root: .
          paths:
            - build/app/outputs/flutter-apk/app-release.apk

  release:
    executor: flutter
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install GitHub CLI
          command: |
            apt-get update && apt-get install -y curl unzip
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            apt-get update && apt-get install -y gh
      - run:
          name: Upload APK to GitHub Release
          command: |
            VERSION_TAG=$(git describe --tags)
            gh release create "$VERSION_TAG" build/app/outputs/flutter-apk/app-release.apk --title "$VERSION_TAG" --notes "Release $VERSION_TAG"

workflows:
  version: 2
  release_workflow:
    jobs:
      - build_android:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
      - release:
          requires:
            - build_android
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
